### ISSUE TITLE
Configuring OAuth2.0 endpoints of external identity provider is not getting reflected

### ISSUE THREAD

**Issue by piraveena** [asgardeo/asgardeo-auth-spa-sdk#30]
**Describe the issue:**
Configuring OAuth2.0 endpoints of external identity provider is not getting reflected. Seems like it is always reading the hardcoded endpoints.

**How to reproduce**
Add below configs.

```
endpoints:{
    authorizationEndpoint:"/authorize",
    tokenEndpoint:"/oauth/token",
    userinfoEndpoint:"/userinfo",
    jwksUri: "/.well-known/jwks.json"
}
```

Even though I configured endpoints externally, it is taking the hardcoded endpoints in the class.

This was the authorization request that I could see in the network trace. (I configured /authorize only)
`https://<idp_domain>/oauth2/authorize?response_type=code&client_id=<client_id>&scope=openid&redirect_uri=https%3A%2F%2Flocalhost%3A4200&response_mode=query&code_challenge_method=S256&code_challenge=ky83tKxV2DHV3GE984HCGOiF0KZSwqPRab1uk1JfAKc`

<img width="585" alt="Screenshot 2021-07-19 at 18 14 38" src="https://user-images.githubusercontent.com/17597293/126161925-5a565bdd-1255-4cd9-81a3-d6a75b6911b0.png">

https://github.com/asgardeo/asgardeo-auth-angular-sdk/issues/81

**Comment by Nirothipan** [comment]
@thivi Is there any possibility to fix this any time soon

**Comment by thivi** [comment]
We will try to fix it within this week and release it.

**Comment by Nirothipan** [comment]
@thivi what is the status of the fix

**Comment by thivi** [comment]
> @thivi what is the status of the fix

A PR has been raised with the fix: https://github.com/asgardeo/asgardeo-auth-spa-sdk/pull/36.

A new release can be triggered once the PR is reviewed and merged.

**Comment by Nirothipan** [comment]
Thanks @thivi

**Comment by thivi** [comment]
Resolved by https://github.com/asgardeo/asgardeo-auth-spa-sdk/issues/35 and https://github.com/asgardeo/asgardeo-auth-spa-sdk/pull/36
