### ISSUE TITLE
Form data not getting set in the requestCustomGrant method

### ISSUE THREAD

**Issue by AyeshW** [asgardeo/asgardeo-auth-spa-sdk#35]
**Describe the issue:**
Form data fields of the `CustomGrantConfig` used in the `requestCustomGrant` method are set to `"[object Promise]"` instead of provided value.

**How to reproduce:**

- Modify the sample apps (ex: asgardeo-react-js-app) to have an additional button near logout button.
- Call the `requestCustomGrant` method in the onClick event of the added button with following configs.
```
const config = {
            attachToken: false,
            data: {
                client_id: "{{clientID}}",
                grant_type: "account_switch",
                scope: "{{scope}}",
                token: "{{token}}",
            },
            id: "account-switch",
            returnResponse: true,
            returnsSession: true,
            signInRequired: true
        };
```

- When click on the added button, you will get a response with 400 response code and form data of the request header will be set as below.

![header](https://user-images.githubusercontent.com/35717171/126271284-9cab30fc-a755-4214-83d6-a480c15750ce.png)

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - SDK Version: 0.1.6

---

### Optional Fields

**Related issues:**
wso2-enterprise/choreo#6561

**Suggested labels:**

**Comment by thivi** [comment]
Resolved by https://github.com/asgardeo/asgardeo-auth-js-sdk/pull/143
